export const KPI_DB_CONNECTION = 'kpi'
export const STAT_DB_CONNECTION = 'stat'
export const GLPI_DB_CONNECTION = 'glpi'
export const FORMS_DB_CONNECTION = 'forms'
export const PORTAL_DB_CONNECTION = 'forms'
